apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: alternacija
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: alternacija
    newName: rg.fr-par.scw.cloud/djnd/alternacija
    newTag: 'latest'
